version: "3"
services:

  guacd:
    image: guacamole/guacd
    restart: always
    networks:
      - guacnet

  db:
    image: glyptodon/guacamole-db-mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      ACCEPT_EULA: "Y"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      GUACAMOLE_DATABASE: guacamole_db
      GUACAMOLE_USERNAME: guacamole_user
      GUACAMOLE_PASSWORD: $GUACPASS
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    restart: always
    volumes:
      - /config
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_SSL_MODE: disabled
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $GUACPASS
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: guacd
    labels:
      - "us.birge.watchtower.enable=true"
    networks:
      - guacnet
    depends_on:
      - db
      - guacd
      - ssl

  ssl:
    image: glyptodon/guacamole-ssl-nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    environment:
      ACCEPT_EULA: "Y"
      GUACAMOLE_HOSTNAME: guacamole
      GUACAMOLE_CONTEXT_PATH: guacamole
      SSL_HOSTNAME: $SSL_HOSTNAME
      SELF_SIGNED: "N"
      LETSENCRYPT_ACCEPT_TOS: "Y"
      LETSENCRYPT_EMAIL: $EMAIL
    networks:
      - guacnet

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "us.birge.watchtower.enable=true"
      
networks:
  guacnet:
