version: "3"

services:
  reverse-proxy:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.birgeresolver.acme.email=admin@birgefuller.com"
      - "--certificatesresolvers.birgeresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.birgeresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.birgeresolver.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "28080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/letsencrypt

  adminer:
    image: adminer
    restart: always
    labels:
      - "traefik.http.routers.adminer.rule=Host(`nyc.birgefuller.com`) && PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer.tls.certresolver=birgeresolver"
      - "traefik.port=8080"
    depends_on:
      - db

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`nyc.birgefuller.com`) && PathPrefix(`/who`)"
      - "traefik.http.routers.whoami.tls.certresolver=birgeresolver"

  db:
    image: keeper/guacamole-db-mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      ACCEPT_EULA: "Y"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      GUACAMOLE_DATABASE: guacamole_db
      GUACAMOLE_USERNAME: guacamole_user
      GUACAMOLE_PASSWORD: $GUACPASS
      GUACAMOLE_ADMIN_PASSWORD: "admin"

  guacd:
    image: guacamole/guacd
    restart: always

  guacamole:
    image: guacamole/guacamole
    restart: always
    volumes:
      - /config
    environment:
      TOTP_ENABLED: "true"
      MYSQL_HOSTNAME: db
      MYSQL_SSL_MODE: disabled
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $GUACPASS
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: guacd
    labels:
      - "traefik.http.routers.guacamole.rule=Host(`nyc.birgefuller.com`) && PathPrefix(`/guacamole`)"
      - "traefik.http.routers.guacamole.tls.certresolver=birgeresolver"
    depends_on:
      - db
      - guacd

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600
 