version: "3"

services:
  guacd:
    image: guacamole/guacd
    restart: always
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    restart: always
    volumes:
      - /config
    environment:
      TOTP_ENABLED: "true"
      MYSQL_HOSTNAME: db
      MYSQL_SSL_MODE: disabled
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $GUACPASS
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: guacd
    networks:
      - guacnet
    depends_on:
      - db
      - guacd
      - ssl

  db:
    image: keeper/guacamole-db-mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      ACCEPT_EULA: "Y"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      GUACAMOLE_DATABASE: guacamole_db
      GUACAMOLE_USERNAME: guacamole_user
      GUACAMOLE_PASSWORD: $GUACPASS
      GUACAMOLE_ADMIN_PASSWORD: "admin"
    networks:
      - guacnet

  ssl:
    image: keeper/guacamole-ssl-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACCEPT_EULA: "Y"
      GUACAMOLE_HOSTNAME: guacamole
      GUACAMOLE_CONTEXT_PATH: guacamole
      SSL_HOSTNAME: $SSL_HOSTNAME
      SELF_SIGNED: "N"
      LETSENCRYPT_ACCEPT_TOS: "Y"
      LETSENCRYPT_EMAIL: $EMAIL
    networks:
      - guacnet

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600
      
networks:
  guacnet:
