version: "3"

services:
  reverse-proxy:
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "28080:8080"
    volumes:
      # So Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`nyc.birgefuller.com`) && PathPrefix(`/who`)"

  db:
    image: keeper/guacamole-db-mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      ACCEPT_EULA: "Y"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      GUACAMOLE_DATABASE: guacamole_db
      GUACAMOLE_USERNAME: guacamole_user
      GUACAMOLE_PASSWORD: $GUACPASS
      GUACAMOLE_ADMIN_PASSWORD: "admin"

  guacd:
    image: guacamole/guacd
    restart: always

  guacamole:
    image: guacamole/guacamole
    restart: always
    volumes:
      - /config
    environment:
      TOTP_ENABLED: "true"
      MYSQL_HOSTNAME: db
      MYSQL_SSL_MODE: disabled
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $GUACPASS
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: guacd
    labels:
      - "traefik.http.routers.guacamole.rule=Host(`nyc.birgefuller.com`) && PathPrefix(`/guacamole`)"
    depends_on:
      - db
      - guacd

  # watchtower:
  #   image: containrrr/watchtower
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 3600
 